all: EX1.exe EX2.exe EX3.exe

EX1.exe: EX1.cpp
	g++ -o EX1.exe EX1.cpp

EX2.exe: EX2.cpp
	g++ -o EX2.exe EX2.cpp

EX3.exe: EX3.cpp
	g++ -o EX3.exe EX3.cpp

EX4.exe: EX4.cpp
	g++ -o EX4.exe EX4.cpp


clean:
	del EX1.exe EX2.exe EX3.exe  EX4.exe
