all: exo1 exo2 exo3 exo4 exo5

exo1:
	g++ exo1.cpp  -o exo1.exe

exo2:
	g++ exo2.cpp  -o exo2.exe

exo3:
	g++ exo3.cpp  -o exo3.exe

exo4:
	g++ exo4.cpp  -o exo4.exe

exo5:
	g++ exo5.cpp  -o exo5.exe

clean:
	del /f exo1.exe exo2.exe exo3.exe exo4.exe exo5.exe